In [166]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

In [167]:
mp_key = "iHKrsQ8aWfQ1QaXnodlQAIOBI4QNOfIj"
mp_id = "mp-2784"

In [168]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id) # Structure cristalline primitive
    conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure() # Structure cristalline conventionelle
    symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations() # Retourne les opérations de symétries
    

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

La représentation du Na2Te dans la maille conventionnelle est reprise ci-dessous. 

In [169]:
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('rotate on')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

J'ai détaillé ci-dessous 3 éléments de symétries, chacune pour un atome différent. Chaque symétrie est définie par sa matrice de rotation (rot) et un vecteur de translation (tau). De plus, il est possible de visualiser les symétries via une représentation 3D. 
(Remarque : si les opérations de symétries ne s'affichent pas, il faut réexécuter les cellules concernées une à une.)

In [174]:
# Première symétrie. 

print("Numéro de l'atome étudié : " + str(1) + " --> (Na)" )
print("(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)")
print("Opérations de symétries associées : \n")

i_atom = 1
i_symmop = 50
symmop = symmops[i_symmop]
print(symmop)
print("\n")

pos_init = conv_struc.sites[6].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))


view2 = quick_view(conv_struc, "packed", conventional = True)
display(view2)


view2.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')



Numéro de l'atome étudié : 1 --> (Na)
(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)
Opérations de symétries associées : 

Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0.5 0.5 0. ]


Position initiale de l'atome : [0.25 0.25 0.25]
Position finale de l'atome : [0.25 0.75 0.25]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Nous pouvons observer que l'opération de symétrie consiste en un axe de rotation d'ordre 4 (rotation de pi/2).

In [173]:
# Deuxième symétrie.

print("Numéro de l'atome étudié : " + str(2) + " --> (Te)" )
print("(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)")
print("Opérations de symétries associées : \n")

i_atom = 2
i_symmop = 100
symmop = symmops[i_symmop]
print(symmop)
print("\n")
pos_init = conv_struc.sites[8].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))

view3 = quick_view(conv_struc, "packed", conventional = True)
display(view3)
view3.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

Numéro de l'atome étudié : 2 --> (Te)
(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)
Opérations de symétries associées : 

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0.5 0.  0.5]


Position initiale de l'atome : [0. 0. 0.]
Position finale de l'atome : [0.5 0.  0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Nous pouvons observer que la symétrie consiste en un axe hélicoïdal 2_1. En effet, une rotation de valeur pi est effectuée sur une 1/2 maille. 

In [172]:
# Troisième symétrie. 
print("Numéro de l'atome étudié : " + str(12) + " --> (Te)" )
print("(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)")
print("Opérations de symétries associées : \n")

i_atom = 12
i_symmop = 153
symmop = symmops[i_symmop]
print(symmop)
print("\n")
pos_init = conv_struc.sites[9].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))

view4 = quick_view(conv_struc, "packed", conventional = True)
display(view4)
view4.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

Numéro de l'atome étudié : 12 --> (Te)
(Remarque : le numéro des atomes est celui qui apparait quand je laisse ma souris sur l'atome.)
Opérations de symétries associées : 

Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0.  0.5 0.5]


Position initiale de l'atome : [0.  0.5 0.5]
Position finale de l'atome : [0. 1. 1.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Nous pouvons observer que la symétrie consiste en une translation ainsi que d'une inversion selon le plan (en bleu sur le dessin) perpendiculaire au vecteur de base 'a'. Les éléments (qui ne sont pas dans le plan) sont donc "réfléchis" par le plan, comme un miroir.